### ISSUE TITLE
403 when call pokemon api

### ISSUE THREAD

**Issue by kelukelugames** [CodeClub/python-curriculum#73] opened 2016-07-14 03:58 UTC
Does this still work for you? I get 403 error when running it.

**Comment by andylolz** [comment] 2016-07-14 08:09
Works for me:
http://pokeapi.co/api/v1/pokemon/25/
http://pokeapi.co/api/v1/sprite/25/

@kelukelugames can you say which URLs were 403ing for you?

**Comment by martinpeck** [comment] 2016-07-14 08:15
It's a known issue with the API. I'll elaborate shortly (currently on a train) but it's to do with the User Agent sent by UrlLib.

Cheers, Martin

**Comment by andylolz** [comment] 2016-07-14 08:54
> it's to do with the User Agent sent by UrlLib.

Ahh, okay.

Identifying “Code Club” in the User-Agent header might be a good idea (I know that sort of thing is considered polite when writing scrapers.) It looks like the live version has the User-Agent set to “something”?

**Comment by martinpeck** [comment] 2016-07-14 10:51
So, we had this question come into the Code Club support e-mail address.

The issue is within the API itself (which as don't own), and we raised it against this repo:
https://github.com/PokeAPI/pokeapi/issues/135#issuecomment-198256744

That issue is closed, but I'm not sure if it means it's also fixed :)

We also, in the mean time, worked around this by changing the UserAgent (in this commit https://github.com/CodeClub/python-curriculum/commit/c1480e85fff4b721667042025a79247912789fa2) resulting in an updated pokeapi.py file (https://github.com/CodeClub/python-curriculum/blob/new-layout/en-GB/pokedex/volunteer-resources/pokeapi.py)

@kelukelugames can you confirm that you're using the updated pokeapi.py file? The main difference is this line here (where the User Agent is set to "something")...

https://github.com/CodeClub/python-curriculum/blob/new-layout/en-GB/pokedex/volunteer-resources/pokeapi.py#L12

**Comment by martinpeck** [comment] 2016-07-14 11:01
@andylolz you're probably right about making the UA say "Code Club". 

I think I said to @rik-cross "we should set the UA to something"...and, quite literally, we did :)

**Comment by kelukelugames** [comment] 2016-07-14 13:25
Hi,

Thanks for the responses. I set the user agent and it worked.

-Kevin

**Comment by martinpeck** [comment] 2016-07-14 13:36
Thanks @kelukelugames.

I'll close this, as the issue is fixed for anyone who downloads the latest .py files. I'll had some comments to the API issue we raised to see why they've closed but not fixed it.

**Closed by martinpeck** 2016-07-14 13:36 UTC
